openapi: 3.0.0
info:
  version: 1.0.0
  title: Taskwave Group
servers:
  - url: http://localhost:3012/api/v1
    description: Development server
  - url: http://localhost:3012/api/v1
    description: Production server
paths:
  /groups:
    post:
      summary: タスクグループ作成
      description: |
        タスクグループを作成する
      operationId: createGroups
      tags:
        - タスクグループ情報
      parameters:
        - name: UserId
          in: header
          required: true
          description: リクエストするユーザーのID
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - properties:
                    group:
                      type: object
                      properties:
                        name:
                          $ref: '#/components/schemas/GroupName'
                        team_id:
                          $ref: '#/components/schemas/TeamId'
                      required:
                        - name
                        - team_id
      responses:
        '200':
          description: |
            リクエスト成功
            
            - タスクグループ情報をレスポンスする
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      id:
                        $ref: '#/components/schemas/GroupId'
                      name:
                        $ref: '#/components/schemas/GroupName'
                      team_id:
                        $ref: '#/components/schemas/TeamId'
                      created_at:
                        $ref: '#/components/schemas/CreatedAt'
                      updated_at:
                        $ref: '#/components/schemas/UpdatedAt'
        '400':
          description: |
            パラメータ不正によるエラー
            
            - グループ名を入力してください
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        '403':
          description: |
            権限不足によるエラー
            
            - 権限がありません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
  /groups/{group_id}:
    patch:
      summary: タスクグループ更新
      description: |
        タスクグループ情報を更新する
      operationId: updateGroups
      tags:
        - タスクグループ情報
      parameters:
        - name: UserId
          in: header
          required: true
          description: リクエストするユーザーのID
          schema:
            type: integer
        - name: group_id
          in: path
          required: true
          description: 更新するタスクグループのID
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - properties:
                    group:
                      type: object
                      properties:
                        name:
                          $ref: '#/components/schemas/GroupName'
                        team_id:
                          $ref: '#/components/schemas/TeamId'
      responses:
        '200':
          description: |
            リクエスト成功
            
            - タスクグループ情報をレスポンスする
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      id:
                        $ref: '#/components/schemas/GroupId'
                      name:
                        $ref: '#/components/schemas/GroupName'
                      team_id:
                        $ref: '#/components/schemas/TeamId'
                      created_at:
                        $ref: '#/components/schemas/CreatedAt'
                      updated_at:
                        $ref: '#/components/schemas/UpdatedAt'
        '400':
          description: |
            設定内容不正によるエラー
            
            - グループ名を入力してください
            - チームIDは変更できません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        '403':
          description: |
            権限不足によるエラー
            
            - 権限がありません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '404':
          description: |
            パラメータ不正によるエラー
            
            - グループは存在しません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
    delete:
      summary: タスクグループ削除
      description: |
        タスクグループを削除する
      operationId: deleteGroups
      tags:
        - タスクグループ情報
      parameters:
        - name: UserId
          in: header
          required: true
          description: リクエストするユーザーのID
          schema:
            type: integer
        - name: group_id
          in: path
          required: true
          description: 更新するタスクグループのID
          schema:
            type: integer
      responses:
        '200':
          description: |
            リクエスト成功
            
            - タスクグループ情報をレスポンスする
          content:
            application/json:
              schema:
                type: object
        '403':
          description: |
            権限不足によるエラー
            
            - 権限がありません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '404':
          description: |
            パラメータ不正によるエラー
            
            - グループは存在しません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
  /groups/{group_id}/edit:
    get:
      summary: タスクグループ詳細
      description: |
        タスクグループ詳細情報を取得する
      operationId: editGroups
      tags:
        - タスクグループ情報
      parameters:
        - name: UserId
          in: header
          required: true
          description: リクエストするユーザーのID
          schema:
            type: integer
        - name: group_id
          in: path
          required: true
          description: 取得するタスクグループのID
          schema:
            type: integer
      responses:
        '200':
          description: |
            リクエスト成功
            
            - タスクグループ情報をレスポンスする
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      id:
                        $ref: '#/components/schemas/GroupId'
                      name:
                        $ref: '#/components/schemas/GroupName'
                      team_name:
                        $ref: '#/components/schemas/TeamName'
                      team_description:
                        $ref: '#/components/schemas/TeamDescription'
                      personal:
                        $ref: '#/components/schemas/TeamPersonalFlag'
                      created_at:
                        $ref: '#/components/schemas/CreatedAt'
                      updated_at:
                        $ref: '#/components/schemas/UpdatedAt'
        '404':
          description: |
            パラメータ不正によるエラー
            
            - グループは存在しません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
components:
  schemas:
    GroupId:
      type: integer
      format: int64
      description: タスクグループID
      example: 1
    GroupName:
      type: string
      description: タスクグループ名
      example: グループ1
    TeamId:
      type: integer
      format: int64
      description: チームID
      example: 1
    TeamName:
      type: string
      description: チーム名
      example: team1
    TeamDescription:
      type: string
      description: チーム説明
      example: サンプルチーム
    TeamPersonalFlag:
      type: boolean
      description: チーム個人フラグ
      example: false
    CreatedAt:
      type: string
      format: date-time
      description: 作成日時
      example: '2022-04-01T12:00:00+09:00'
    UpdatedAt:
      type: string
      format: date-time
      description: 更新日時
      example: '2022-04-01T23:59:59+09:00'
    Error400:
      type: object
      required:
        - error_code
        - error_message
      properties:
        title:
          type: string
          example: タスク作成処理
        status:
          type: integer
          format: int32
          example: 400
        error_code:
          type: string
          example: TLM_010101
        error_message:
          type: array
          items:
            type: string
            example: 不正なパラメータです
    Error403:
      type: object
      required:
        - error_code
        - error_message
      properties:
        title:
          type: string
          example: タスク作成処理
        status:
          type: integer
          format: int32
          example: 403
        error_code:
          type: string
          example: TLM_000002
        error_message:
          type: array
          items:
            type: string
            example: 権限がありません
    Error404:
      type: object
      required:
        - error_code
        - error_message
      properties:
        title:
          type: string
          example: グループ情報更新処理
        status:
          type: integer
          format: int32
          example: 404
        error_code:
          type: string
          example: TLM_000001
        error_message:
          type: array
          items:
            type: string
            example: グループは存在しません
